### ISSUE TITLE
gracefully treat conflicting export config

### ISSUE THREAD

**Issue by nico202** [alejandrogallo/papis#20]
I tried exporting the biblography without reading too much the help info

> papis export --json --folder /tmp/newexp -a        
   
```                                                                                
Traceback (most recent call last):                                                                                                                                                               
  File "/home/IITaudio/tmp/bin/papis", line 11, in <module>
    load_entry_point('papis==0.4.6', 'console_scripts', 'papis')()
  File "/home/IITaudio/tmp/lib/python3.4/site-packages/papis/main.py", line 24, in main
    papis.commands.main()
  File "/home/IITaudio/tmp/lib/python3.4/site-packages/papis/commands/__init__.py", line 210, in main
    commands["default"].main()
  File "/home/IITaudio/tmp/lib/python3.4/site-packages/papis/commands/default.py", line 153, in main
    commands[self.args.command].main()
  File "/home/IITaudio/tmp/lib/python3.4/site-packages/papis/commands/export.py", line 135, in main
    return self.args.out.write(                                                                                                                                                                  
AttributeError: 'str' object has no attribute 'write'                                                                                                                                            
(tmp)                         
```

**Comment by alejandrogallo** [comment]
True, it should check better for user flags, I agree, will fix today.

**Comment by alejandrogallo** [comment]
It does the check now!
