### ISSUE TITLE
Choose option screen broken by left/right arrow

### ISSUE THREAD

**Issue by mftrhu** [alejandrogallo/papis#3]
The screen to choose papers or files entered via `papis open`, `papis edit`, or by choosing open in the rofi GUI when more than one file is present, allows for both the right and left arrows to be pressed - netting me `ąĄ` and erasing the content of the screen minus the `Pick:` prompt - which then results in a `IndexError` if this "choice" is confirmed.

Full traceback:
```
Traceback (most recent call last):
  File "/usr/bin/papis", line 11, in <module>
    load_entry_point('papis==0.1.3', 'console_scripts', 'papis')()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/main.py", line 24, in main
    papis.commands.main()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/__init__.py", line 211, in main
    commands["default"].main()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/default.py", line 137, in main
    commands[self.args.command].main()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/open.py", line 44, in main
    document = self.pick(documents)
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/__init__.py", line 307, in pick
    pick_config
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/api.py", line 116, in pick
    return papis.pick.pick(options, **pick_config)
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/pick.py", line 246, in pick
    return picker.start()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/pick.py", line 223, in start
    return curses.wrapper(self._start)
  File "/usr/lib64/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/pick.py", line 216, in _start
    return self.run_loop()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/pick.py", line 188, in run_loop
    return self.get_selected()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/pick.py", line 78, in get_selected
    return self.get_filtered_options()[self.index]
IndexError: list index out of range
```

**Comment by alejandrogallo** [comment]
Yes, true, it is fixed now! In passing I also fixed the fact that one could not input ( or [.
Thank you sooo much!
