### ISSUE TITLE
papis add fails with FileNotFoundError

### ISSUE THREAD

**Issue by michaelplews** [alejandrogallo/papis#37]
```bash
papis add --from-doi 10.1021/nn4005022 /tmp/paper.pdf 
```

Results in:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/papis", line 9, in <module>
    load_entry_point('papis==0.5.0', 'console_scripts', 'papis')()
  File "/home/mike/Software/papis/papis/main.py", line 24, in main
    papis.commands.main()
  File "/home/mike/Software/papis/papis/commands/__init__.py", line 210, in main
    commands["default"].main()
  File "/home/mike/Software/papis/papis/commands/default.py", line 167, in main
    commands[self.args.command].main()
  File "/home/mike/Software/papis/papis/commands/add.py", line 509, in main
    suffix=string_append
  File "/home/mike/Software/papis/papis/commands/add.py", line 228, in get_file_name
    "." + papis.utils.guess_file_extension(original_filename)
  File "/home/mike/Software/papis/papis/utils.py", line 601, in guess_file_extension
    if eval("is_%s" % ext)(file_description):
  File "/home/mike/Software/papis/papis/utils.py", line 585, in is_pdf
    return file_is(file_description, 'pdf')
  File "/home/mike/Software/papis/papis/utils.py", line 565, in file_is
    r".*%s.*" % fmt, magic.from_file(file_description, mime=True),
  File "/usr/local/lib/python3.5/dist-packages/magic.py", line 131, in from_file
    return m.from_file(filename)
  File "/usr/local/lib/python3.5/dist-packages/magic.py", line 81, in from_file
    with open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'paper.pdf'

```

Is the full filepath not being passed to the `magic` function?

**Comment by alejandrogallo** [comment]
Ups! That's bad, it's exactly what you are saying, only the filename was being passed to the function.
Now it's fixed! Thank you again!
