### ISSUE TITLE
file-name option and adding files with incomplete metadata

### ISSUE THREAD

**Issue by dsanson** [alejandrogallo/papis#39]
If I set

    file-name = {doc[author]}{doc[year]}

in my config, I can't add new documents using a command like,

    papis add file.pdf --name "John Smith" --title "An Article"

presumably because papis tries to access the doc[year], but the metadata does not yet include a year. Seems like it should have a way of gracefully falling back to an incomplete file-name in situations like this.

```
Traceback (most recent call last):
  File "/usr/local/bin/papis", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/papis/main.py", line 24, in main
    papis.commands.main()
  File "/usr/local/lib/python3.6/site-packages/papis/commands/__init__.py", line 210, in main
    commands["default"].main()
  File "/usr/local/lib/python3.6/site-packages/papis/commands/default.py", line 167, in main
    commands[self.args.command].main()
  File "/usr/local/lib/python3.6/site-packages/papis/commands/add.py", line 509, in main
    suffix=string_append
  File "/usr/local/lib/python3.6/site-packages/papis/commands/add.py", line 228, in get_file_name
    "." + papis.utils.guess_file_extension(original_filepath)
  File "/usr/local/lib/python3.6/site-packages/papis/utils.py", line 68, in format_doc
    return python_format.format(**{doc: document})
KeyError: 'year'
```

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Hi!
indeed! Very well seen!

**Comment by alejandrogallo** [comment]
I updated papis version to 0.5.2 to pypi with this fix, among others, so now this fix is obtainable via pip too.
