### ISSUE TITLE
gui --rofi crashing on delete

### ISSUE THREAD

**Issue by mftrhu** [alejandrogallo/papis#6]
As per the title, when deleting something from within the rofi GUI `papis` crashes. The selected item __is__ deleted, in any case.

Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/papis", line 11, in <module>
    load_entry_point('papis==0.1.3', 'console_scripts', 'papis')()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/main.py", line 24, in main
    papis.commands.main()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/__init__.py", line 210, in main
    commands["default"].main()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/default.py", line 137, in main
    commands[self.args.command].main()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/gui.py", line 53, in main
    return self.rofi_main()
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/commands/gui.py", line 36, in rofi_main
    return papis.gui.rofi.Gui().main(self.documents)
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/gui/rofi.py", line 151, in main
    self.delete(self.documents[i])
  File "/usr/lib/python3.4/site-packages/papis-0.1.3-py3.4.egg/papis/gui/rofi.py", line 167, in delete
    self.documents = self.fetch_documents()
AttributeError: 'Gui' object has no attribute 'fetch_documents'
```

**Comment by alejandrogallo** [comment]
True, good catch, thank you very much for your time!
